# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Using Ubuntu 18.04 bionic
  config.vm.box = "bento/ubuntu-18.04"

  # Use IP private IP address 192.168.33.10
  config.vm.network "private_network", ip: "192.168.33.10"

  # Use ansible as VM provisioner
  config.vm.provision "ansible" do |ansible|
    # Use playbook.yml file to provision
    ansible.playbook = "playbook.yml"
    # Use Python3 
    ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
  end # End provisioner
end # End Vagrantfile